const fs = require('fs');
const path = require('path');

class MasterView {
  constructor(config = {}) {
    this.docManager = require('./documentManager');
    this.versionControl = require('./versionControl');
    this.docsDir = config.docsDir || path.join(process.cwd(), 'docs');
    this.masterFile = config.masterFile || path.join(this.docsDir, 'master.md');
    this.viewsDir = path.join(this.docsDir, 'views');

    this.ensureDirectories();
  }

  ensureDirectories() {
    [this.docsDir, this.viewsDir].forEach(dir => {
      if (!fs.existsSync(dir)) {
        fs.mkdirSync(dir, { recursive: true });
      }
    });
  }

  /**
   * Generate and return master view
   */
  getMasterView() {
    if (!fs.existsSync(this.masterFile)) {
      return null;
    }

    const content = fs.readFileSync(this.masterFile, 'utf8');
    const metadata = this.extractMetadata(content);

    return {
      content,
      metadata,
      path: this.masterFile,
      lastModified: fs.statSync(this.masterFile).mtime
    };
  }

  /**
   * Update master view
   */
  updateMasterView(chunks) {
    let masterContent = this.buildMasterContent(chunks);

    fs.writeFileSync(this.masterFile, masterContent);

    return {
      path: this.masterFile,
      updated: new Date().toISOString(),
      chunkCount: chunks.length
    };
  }

  /**
   * Build master content from chunks
   */
  buildMasterContent(chunks) {
    const now = new Date().toISOString();

    let content = '# Master Document\n\n';
    content += `> **Living Documentation System**\n`;
    content += `> Last Updated: ${now}\n`;
    content += `> Total Chunks: ${chunks.length}\n\n`;
    content += '---\n\n';

    // Table of Contents
    content += '## Table of Contents\n\n';
    chunks.forEach((chunk, index) => {
      const anchor = this.slugify(chunk.name);
      content += `${index + 1}. [${chunk.name}](#${anchor})\n`;
    });
    content += '\n---\n\n';

    // Content sections
    chunks.forEach((chunk, index) => {
      const anchor = this.slugify(chunk.name);
      content += `<a name="${anchor}"></a>\n`;
      content += `## ${index + 1}. ${chunk.name}\n\n`;

      if (chunk.metadata) {
        content += `*Last modified: ${chunk.metadata.updatedAt || chunk.metadata.createdAt}*\n\n`;
      }

      content += `${chunk.content}\n\n`;
      content += `<!-- CHUNK_ID: ${chunk.id} -->\n`;
      content += `<!-- CHUNK_HASH: ${chunk.hash} -->\n\n`;
      content += '---\n\n';
    });

    // Footer
    content += `\n---\n\n`;
    content += `*Generated by Living Documentation System*\n`;
    content += `*${now}*\n`;

    return content;
  }

  /**
   * Create a filtered view
   */
  createFilteredView(name, filter) {
    const DocumentManager = require('./documentManager');
    const docManager = new DocumentManager();
    const allChunks = docManager.getAllChunks();

    const filteredChunks = allChunks.filter(filter);
    const viewContent = this.buildMasterContent(filteredChunks);

    const viewPath = path.join(this.viewsDir, `${name}.md`);
    fs.writeFileSync(viewPath, viewContent);

    return {
      name,
      path: viewPath,
      chunkCount: filteredChunks.length
    };
  }

  /**
   * Create a view by tags
   */
  createTagView(tag) {
    return this.createFilteredView(`tag-${tag}`, chunk => {
      return chunk.metadata && chunk.metadata.tags && chunk.metadata.tags.includes(tag);
    });
  }

  /**
   * Create a view by date range
   */
  createDateRangeView(startDate, endDate, name = null) {
    const viewName = name || `daterange-${startDate}-${endDate}`;

    return this.createFilteredView(viewName, chunk => {
      const updatedAt = new Date(chunk.metadata.updatedAt);
      return updatedAt >= new Date(startDate) && updatedAt <= new Date(endDate);
    });
  }

  /**
   * Get all available views
   */
  getAllViews() {
    if (!fs.existsSync(this.viewsDir)) {
      return [];
    }

    const files = fs.readdirSync(this.viewsDir);
    return files
      .filter(file => file.endsWith('.md'))
      .map(file => {
        const filePath = path.join(this.viewsDir, file);
        const stats = fs.statSync(filePath);

        return {
          name: file.replace('.md', ''),
          path: filePath,
          lastModified: stats.mtime,
          size: stats.size
        };
      });
  }

  /**
   * Export master view to different formats
   */
  exportView(format = 'markdown', outputPath = null) {
    const view = this.getMasterView();

    if (!view) {
      throw new Error('Master view not found');
    }

    if (format === 'markdown') {
      const output = outputPath || path.join(this.docsDir, 'export.md');
      fs.writeFileSync(output, view.content);
      return output;
    } else if (format === 'json') {
      const DocumentManager = require('./documentManager');
      const docManager = new DocumentManager();
      const chunks = docManager.getAllChunks();

      const jsonData = {
        generated: new Date().toISOString(),
        chunks: chunks.map(chunk => ({
          id: chunk.id,
          name: chunk.name,
          content: chunk.content,
          metadata: chunk.metadata,
          hash: chunk.hash
        }))
      };

      const output = outputPath || path.join(this.docsDir, 'export.json');
      fs.writeFileSync(output, JSON.stringify(jsonData, null, 2));
      return output;
    } else if (format === 'html') {
      const marked = require('marked');
      const html = marked.parse(view.content);

      const htmlDoc = `
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Living Documentation</title>
    <style>
        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, sans-serif;
            line-height: 1.6;
            max-width: 900px;
            margin: 0 auto;
            padding: 20px;
            color: #333;
        }
        h1, h2, h3 { color: #2c3e50; }
        code {
            background: #f4f4f4;
            padding: 2px 6px;
            border-radius: 3px;
        }
        pre {
            background: #f4f4f4;
            padding: 15px;
            border-radius: 5px;
            overflow-x: auto;
        }
        blockquote {
            border-left: 4px solid #3498db;
            margin: 0;
            padding-left: 20px;
            color: #555;
        }
        hr { border: 0; border-top: 1px solid #ddd; margin: 30px 0; }
    </style>
</head>
<body>
${html}
</body>
</html>
      `;

      const output = outputPath || path.join(this.docsDir, 'export.html');
      fs.writeFileSync(output, htmlDoc);
      return output;
    } else {
      throw new Error(`Unsupported format: ${format}`);
    }
  }

  /**
   * Extract metadata from content
   */
  extractMetadata(content) {
    const lines = content.split('\n');
    const metadata = {};

    lines.forEach(line => {
      if (line.includes('Last Updated:')) {
        metadata.lastUpdated = line.split('Last Updated:')[1].trim();
      }
      if (line.includes('Total Chunks:')) {
        metadata.totalChunks = parseInt(line.split('Total Chunks:')[1].trim());
      }
    });

    return metadata;
  }

  /**
   * Create URL-friendly slug
   */
  slugify(text) {
    return text
      .toLowerCase()
      .replace(/[^\w\s-]/g, '')
      .replace(/\s+/g, '-')
      .replace(/-+/g, '-')
      .trim();
  }

  /**
   * Search within master view
   */
  search(query) {
    const view = this.getMasterView();

    if (!view) {
      return [];
    }

    const lines = view.content.split('\n');
    const results = [];
    let currentChunk = null;

    lines.forEach((line, index) => {
      const chunkMatch = line.match(/<!-- CHUNK_ID: (.+) -->/);
      if (chunkMatch) {
        currentChunk = chunkMatch[1];
      }

      if (line.toLowerCase().includes(query.toLowerCase())) {
        results.push({
          line: index + 1,
          content: line,
          chunkId: currentChunk
        });
      }
    });

    return results;
  }
}

module.exports = MasterView;
